// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtyjewzulygflrrfszre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0eWpld3p1bHlnZmxycmZzenJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDcyODQsImV4cCI6MjA3MDMyMzI4NH0.3hJ5ELdTXI1dPFLmbusGDsbR7hC5v1LO6u7IdjQyO3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});